version: '3.8'
services:
  app:
    image: 'juronja/tincture-calculator:latest'
    container_name: tincture-calculator
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '7474:80'
