name: Docker Image CI

on:
  push:
    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag juronja/alcohol-dilution-calculator:latest
    - name: push
      run: docker login -u juronja -p ${{ secrets.DOCKER_HUB_TOKEN }} && docker push juronja/alcohol-dilution-calculator:latest

